# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-02 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_ruangan', '0002_auto_20210701_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ruanganterpinjam',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
